config = {
    "mySQL_Logs": "D:/Documents/PIR\\mySQL_Logs",
    "mySQL_General_Logs": "D:/Documents/PIR\\mySQL_General_Logs",
    "mySQL_Binary_Logs": "D:/Documents/PIR\\mySQL_Binary_Logs",
    "mySQL_Query_Logs": "D:/Documents/PIR\\mySQL_Query_Logs",
    "Installation_Logs": "D:/Documents/PIR\\Installation_Logs",
    "Automated_Pipeline_Logs": "D:/Documents/PIR\\Automated_Pipeline_Logs",
    "Listener_Logs": "D:/Documents/PIR\\Listener_Logs",
    "PIR_data_repository": "D:/Documents/PIR\\PIR_data_repository",
    "Listener_bats": "D:/Documents/PIR\\Listener_bats",
    "Raw": "D:/Documents/PIR\\PIR_data_repository\\Raw",
    "Processed": "D:/Documents/PIR\\PIR_data_repository\\Processed",
    "Unprocessed": "D:/Documents/PIR\\PIR_data_repository\\Unprocessed",
    "R_Path": "D:/R/R-4.2.2/bin/Rscript.exe",
    "dbusername": "",
    "dbpassword": "",
    "dbhost": "localhost",
    "dbport": 0,
    "dbpath": "D:\\Documents\\PIR"
}